name: colog_v3
description: Colog V3 Flutter application
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.3
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  args: ^2.4.2
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
